// automatically generated by the FlatBuffers compiler, do not modify

package org.odict.java.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Entry extends Table {
  public static Entry getRootAsEntry(ByteBuffer _bb) { return getRootAsEntry(_bb, new Entry()); }
  public static Entry getRootAsEntry(ByteBuffer _bb, Entry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Entry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String term() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer termAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public Etymology etymologies(int j) { return etymologies(new Etymology(), j); }
  public Etymology etymologies(Etymology obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int etymologiesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createEntry(FlatBufferBuilder builder,
      int termOffset,
      int etymologiesOffset) {
    builder.startObject(2);
    Entry.addEtymologies(builder, etymologiesOffset);
    Entry.addTerm(builder, termOffset);
    return Entry.endEntry(builder);
  }

  public static void startEntry(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addTerm(FlatBufferBuilder builder, int termOffset) { builder.addOffset(0, termOffset, 0); }
  public static void addEtymologies(FlatBufferBuilder builder, int etymologiesOffset) { builder.addOffset(1, etymologiesOffset, 0); }
  public static int createEtymologiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEtymologiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endEntry(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // term
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) { return compareStrings(__offset(4, o1, _bb), __offset(4, o2, _bb), _bb); }

  public static Entry __lookup_by_key(int vectorLocation, String key, ByteBuffer bb) {
    byte[] byteKey = key.getBytes(Table.UTF8_CHARSET.get());
    int span = bb.getInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = compareStrings(__offset(4, bb.array().length - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new Entry().__assign(tableOffset, bb);
      }
    }
    return null;
  }
}

