// automatically generated by the FlatBuffers compiler, do not modify

package org.odict.java.schema;

public final class POS {
  private POS() { }
  public static final byte verb = 0;
  public static final byte noun = 1;
  public static final byte adj = 2;
  public static final byte pronoun = 3;
  public static final byte adv = 4;
  public static final byte prep = 5;
  public static final byte conj = 6;
  public static final byte intj = 7;
  public static final byte prefix = 8;
  public static final byte suffix = 9;
  public static final byte particle = 10;

  public static final String[] names = { "verb", "noun", "adj", "pronoun", "adv", "prep", "conj", "intj", "prefix", "suffix", "particle", };

  public static String name(int e) { return names[e]; }
}

